/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectImageMulticlassForm model module.
* @module model/CollectImageMulticlassForm
* @version 1.0.0
*/
export default class CollectImageMulticlassForm {
    /**
    * Constructs a new <code>CollectImageMulticlassForm</code>.
    * @alias module:model/CollectImageMulticlassForm
    * @class
    */

    constructor() {
        
        AnyOfbody1.call(this);
        
    }

    /**
    * Constructs a <code>CollectImageMulticlassForm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectImageMulticlassForm} obj Optional instance to populate.
    * @return {module:model/CollectImageMulticlassForm} The populated <code>CollectImageMulticlassForm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectImageMulticlassForm();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], File);
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * image file to be uploaded
    * @member {File} image
    */
    'image' = undefined;
    /**
    * category in which the image needs to be classified
    * @member {String} category
    */
    'category' = undefined;

    // Implement AnyOfbody1 interface:
    


}
