/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectImageMulticlass model module.
* @module model/CollectImageMulticlass
* @version 1.0.0
*/
export default class CollectImageMulticlass {
    /**
    * Constructs a new <code>CollectImageMulticlass</code>.
    * @alias module:model/CollectImageMulticlass
    * @class
    */

    constructor() {
        
        AnyOfbody.call(this);
        
    }

    /**
    * Constructs a <code>CollectImageMulticlass</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectImageMulticlass} obj Optional instance to populate.
    * @return {module:model/CollectImageMulticlass} The populated <code>CollectImageMulticlass</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectImageMulticlass();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * public url of the image to be uploaded
    * @member {String} image
    */
    'image' = undefined;
    /**
    * category in which the image needs to be classified
    * @member {String} category
    */
    'category' = undefined;

    // Implement AnyOfbody interface:
    


}
