/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectTextMulticlass model module.
* @module model/CollectTextMulticlass
* @version 1.0.0
*/
export default class CollectTextMulticlass {
    /**
    * Constructs a new <code>CollectTextMulticlass</code>.
    * @alias module:model/CollectTextMulticlass
    * @class
    */

    constructor() {
        
        AnyOfbody.call(this);
        
    }

    /**
    * Constructs a <code>CollectTextMulticlass</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectTextMulticlass} obj Optional instance to populate.
    * @return {module:model/CollectTextMulticlass} The populated <code>CollectTextMulticlass</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectTextMulticlass();
                        
            
            if (data.hasOwnProperty('free_text')) {
                obj['free_text'] = ApiClient.convertToType(data['free_text'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
        }
        return obj;
    }

    /**
    * text corpus to be collected
    * @member {String} free_text
    */
    'free_text' = undefined;
    /**
    * @member {String} category
    */
    'category' = undefined;

    // Implement AnyOfbody interface:
    


}
