/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectImageMultilabelForm model module.
* @module model/CollectImageMultilabelForm
* @version 1.0.0
*/
export default class CollectImageMultilabelForm {
    /**
    * Constructs a new <code>CollectImageMultilabelForm</code>.
    * @alias module:model/CollectImageMultilabelForm
    * @class
    */

    constructor() {
        
        AnyOfbody1.call(this);
        
    }

    /**
    * Constructs a <code>CollectImageMultilabelForm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectImageMultilabelForm} obj Optional instance to populate.
    * @return {module:model/CollectImageMultilabelForm} The populated <code>CollectImageMultilabelForm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectImageMultilabelForm();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], File);
            }
            if (data.hasOwnProperty('tag1')) {
                obj['tag1'] = ApiClient.convertToType(data['tag1'], 'String');
            }
            if (data.hasOwnProperty('tag2')) {
                obj['tag2'] = ApiClient.convertToType(data['tag2'], 'String');
            }
        }
        return obj;
    }

    /**
    * image file to be uploaded
    * @member {File} image
    */
    'image' = undefined;
    /**
    * custom defined category of the image (can be multiple)
    * @member {String} tag1
    */
    'tag1' = undefined;
    /**
    * custom defined category of the image (can be multiple)
    * @member {String} tag2
    */
    'tag2' = undefined;

    // Implement AnyOfbody1 interface:
    


}
