/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectImageMultilabel model module.
* @module model/CollectImageMultilabel
* @version 1.0.0
*/
export default class CollectImageMultilabel {
    /**
    * Constructs a new <code>CollectImageMultilabel</code>.
    * @alias module:model/CollectImageMultilabel
    * @class
    */

    constructor() {
        
        AnyOfbody.call(this);
        
    }

    /**
    * Constructs a <code>CollectImageMultilabel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectImageMultilabel} obj Optional instance to populate.
    * @return {module:model/CollectImageMultilabel} The populated <code>CollectImageMultilabel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectImageMultilabel();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
            if (data.hasOwnProperty('tag1')) {
                obj['tag1'] = ApiClient.convertToType(data['tag1'], 'String');
            }
            if (data.hasOwnProperty('tag2')) {
                obj['tag2'] = ApiClient.convertToType(data['tag2'], 'String');
            }
        }
        return obj;
    }

    /**
    * public url of the image to be uploaded
    * @member {String} image
    */
    'image' = undefined;
    /**
    * custom defined category of the image (can be multiple)
    * @member {String} tag1
    */
    'tag1' = undefined;
    /**
    * custom defined category of the image (can be multiple)
    * @member {String} tag2
    */
    'tag2' = undefined;

    // Implement AnyOfbody interface:
    


}
