/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The CollectTextMultilabel model module.
* @module model/CollectTextMultilabel
* @version 1.0.0
*/
export default class CollectTextMultilabel {
    /**
    * Constructs a new <code>CollectTextMultilabel</code>.
    * @alias module:model/CollectTextMultilabel
    * @class
    */

    constructor() {
        
        AnyOfbody.call(this);
        
    }

    /**
    * Constructs a <code>CollectTextMultilabel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CollectTextMultilabel} obj Optional instance to populate.
    * @return {module:model/CollectTextMultilabel} The populated <code>CollectTextMultilabel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CollectTextMultilabel();
                        
            
            if (data.hasOwnProperty('free_text')) {
                obj['free_text'] = ApiClient.convertToType(data['free_text'], 'String');
            }
            if (data.hasOwnProperty('tag1')) {
                obj['tag1'] = ApiClient.convertToType(data['tag1'], 'String');
            }
            if (data.hasOwnProperty('tag2')) {
                obj['tag2'] = ApiClient.convertToType(data['tag2'], 'String');
            }
        }
        return obj;
    }

    /**
    * text corpus to be collected
    * @member {String} free_text
    */
    'free_text' = undefined;
    /**
    * custom defined category of the text (can be multiple)
    * @member {String} tag1
    */
    'tag1' = undefined;
    /**
    * custom defined category of the text (can be multiple)
    * @member {String} tag2
    */
    'tag2' = undefined;

    // Implement AnyOfbody interface:
    


}
