/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ImageInference model module.
* @module model/ImageInference
* @version 1.0.0
*/
export default class ImageInference {
    /**
    * Constructs a new <code>ImageInference</code>.
    * @alias module:model/ImageInference
    * @class
    */

    constructor() {
        
        AnyOfbody2.call(this);
        
    }

    /**
    * Constructs a <code>ImageInference</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ImageInference} obj Optional instance to populate.
    * @return {module:model/ImageInference} The populated <code>ImageInference</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ImageInference();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], 'String');
            }
        }
        return obj;
    }

    /**
    * public url of the image to be inferenced
    * @member {String} image
    */
    'image' = undefined;

    // Implement AnyOfbody2 interface:
    


}
