/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectDetectionObjects from './ObjectDetectionObjects';

/**
* The ObjectDetectionForm model module.
* @module model/ObjectDetectionForm
* @version 1.0.0
*/
export default class ObjectDetectionForm {
    /**
    * Constructs a new <code>ObjectDetectionForm</code>.
    * @alias module:model/ObjectDetectionForm
    * @class
    */

    constructor() {
        
        AnyOfbody1.call(this);
        
    }

    /**
    * Constructs a <code>ObjectDetectionForm</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ObjectDetectionForm} obj Optional instance to populate.
    * @return {module:model/ObjectDetectionForm} The populated <code>ObjectDetectionForm</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectDetectionForm();
                        
            
            if (data.hasOwnProperty('image')) {
                obj['image'] = ApiClient.convertToType(data['image'], File);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'String');
            }
            if (data.hasOwnProperty('objects')) {
                obj['objects'] = ApiClient.convertToType(data['objects'], [ObjectDetectionObjects]);
            }
        }
        return obj;
    }

    /**
    * image file to be uploaded
    * @member {File} image
    */
    'image' = undefined;
    /**
    * height of the image
    * @member {String} height
    */
    'height' = undefined;
    /**
    * width of the image
    * @member {String} width
    */
    'width' = undefined;
    /**
    * @member {Array.<module:model/ObjectDetectionObjects>} objects
    */
    'objects' = undefined;

    // Implement AnyOfbody1 interface:
    


}
