/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ObjectDetectionImage model module.
* @module model/ObjectDetectionImage
* @version 1.0.0
*/
export default class ObjectDetectionImage {
    /**
    * Constructs a new <code>ObjectDetectionImage</code>.
    * @alias module:model/ObjectDetectionImage
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ObjectDetectionImage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ObjectDetectionImage} obj Optional instance to populate.
    * @return {module:model/ObjectDetectionImage} The populated <code>ObjectDetectionImage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectDetectionImage();
                        
            
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'String');
            }
        }
        return obj;
    }

    /**
    * public url of the image to be uploaded
    * @member {String} url
    */
    'url' = undefined;
    /**
    * height of the image
    * @member {String} height
    */
    'height' = undefined;
    /**
    * width of the image
    * @member {String} width
    */
    'width' = undefined;




}
