/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ObjectDetectionObjects model module.
* @module model/ObjectDetectionObjects
* @version 1.0.0
*/
export default class ObjectDetectionObjects {
    /**
    * Constructs a new <code>ObjectDetectionObjects</code>.
    * @alias module:model/ObjectDetectionObjects
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ObjectDetectionObjects</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ObjectDetectionObjects} obj Optional instance to populate.
    * @return {module:model/ObjectDetectionObjects} The populated <code>ObjectDetectionObjects</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectDetectionObjects();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('x_min')) {
                obj['x_min'] = ApiClient.convertToType(data['x_min'], 'String');
            }
            if (data.hasOwnProperty('y_min')) {
                obj['y_min'] = ApiClient.convertToType(data['y_min'], 'String');
            }
            if (data.hasOwnProperty('x_max')) {
                obj['x_max'] = ApiClient.convertToType(data['x_max'], 'String');
            }
            if (data.hasOwnProperty('y_max')) {
                obj['y_max'] = ApiClient.convertToType(data['y_max'], 'String');
            }
        }
        return obj;
    }

    /**
    * name of the object
    * @member {String} name
    */
    'name' = undefined;
    /**
    * value of the x-coordinate at the top-left corner of the bounding box
    * @member {String} x_min
    */
    'x_min' = undefined;
    /**
    * value of the x-coordinate at the top-left corner of the bounding box
    * @member {String} y_min
    */
    'y_min' = undefined;
    /**
    * value of the x-coordinate at the bottom-right corner of the bounding box
    * @member {String} x_max
    */
    'x_max' = undefined;
    /**
    * value of the x-coordinate at the bottom-right corner of the bounding box
    * @member {String} y_max
    */
    'y_max' = undefined;




}
