/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TextInference model module.
* @module model/TextInference
* @version 1.0.0
*/
export default class TextInference {
    /**
    * Constructs a new <code>TextInference</code>.
    * @alias module:model/TextInference
    * @class
    */

    constructor() {
        
        AnyOfbody2.call(this);
        
    }

    /**
    * Constructs a <code>TextInference</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextInference} obj Optional instance to populate.
    * @return {module:model/TextInference} The populated <code>TextInference</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextInference();
                        
            
            if (data.hasOwnProperty('free_text')) {
                obj['free_text'] = ApiClient.convertToType(data['free_text'], 'String');
            }
        }
        return obj;
    }

    /**
    * text corpus to be inferenced
    * @member {String} free_text
    */
    'free_text' = undefined;

    // Implement AnyOfbody2 interface:
    


}
