/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TextExtractionEntity1 model module.
* @module model/TextExtractionEntity1
* @version 1.0.0
*/
export default class TextExtractionEntity1 {
    /**
    * Constructs a new <code>TextExtractionEntity1</code>.
    * @alias module:model/TextExtractionEntity1
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TextExtractionEntity1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextExtractionEntity1} obj Optional instance to populate.
    * @return {module:model/TextExtractionEntity1} The populated <code>TextExtractionEntity1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextExtractionEntity1();
                        
            
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('idx')) {
                obj['idx'] = ApiClient.convertToType(data['idx'], 'String');
            }
        }
        return obj;
    }

    /**
    * custom defined entity that needs to be extrcated from the text (can be multiple)
    * @member {String} key
    */
    'key' = undefined;
    /**
    * starting index for NAMED_ENTITY
    * @member {String} idx
    */
    'idx' = undefined;




}
