/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TextInferenceBatch model module.
* @module model/TextInferenceBatch
* @version 1.0.0
*/
export default class TextInferenceBatch {
    /**
    * Constructs a new <code>TextInferenceBatch</code>.
    * @alias module:model/TextInferenceBatch
    * @class
    */

    constructor() {
        
        AnyOfbody3.call(this);
        
    }

    /**
    * Constructs a <code>TextInferenceBatch</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextInferenceBatch} obj Optional instance to populate.
    * @return {module:model/TextInferenceBatch} The populated <code>TextInferenceBatch</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextInferenceBatch();
                        
            
            if (data.hasOwnProperty('free_text')) {
                obj['free_text'] = ApiClient.convertToType(data['free_text'], File);
            }
        }
        return obj;
    }

    /**
    * free text file containings corpus of texts to be inferenced
    * @member {File} free_text
    */
    'free_text' = undefined;

    // Implement AnyOfbody3 interface:
    


}
