/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TextExtractionEntity1 from './TextExtractionEntity1';

/**
* The TextExtraction model module.
* @module model/TextExtraction
* @version 1.0.0
*/
export default class TextExtraction {
    /**
    * Constructs a new <code>TextExtraction</code>.
    * @alias module:model/TextExtraction
    * @class
    */

    constructor() {
        
        AnyOfbody.call(this);
        
    }

    /**
    * Constructs a <code>TextExtraction</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TextExtraction} obj Optional instance to populate.
    * @return {module:model/TextExtraction} The populated <code>TextExtraction</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TextExtraction();
                        
            
            if (data.hasOwnProperty('free_text')) {
                obj['free_text'] = ApiClient.convertToType(data['free_text'], 'String');
            }
            if (data.hasOwnProperty('entity1')) {
                obj['entity1'] = ApiClient.convertToType(data['entity1'], [TextExtractionEntity1]);
            }
            if (data.hasOwnProperty('entity2')) {
                obj['entity2'] = ApiClient.convertToType(data['entity2'], [TextExtractionEntity1]);
            }
        }
        return obj;
    }

    /**
    * text corpus to be collected
    * @member {String} free_text
    */
    'free_text' = undefined;
    /**
    * @member {Array.<module:model/TextExtractionEntity1>} entity1
    */
    'entity1' = undefined;
    /**
    * @member {Array.<module:model/TextExtractionEntity1>} entity2
    */
    'entity2' = undefined;

    // Implement AnyOfbody interface:
    


}
