/**
 * Skyl.ai API Documentation
 * This is Skyl.ai API documentation.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AnyOfbody from './model/AnyOfbody';
import AnyOfbody1 from './model/AnyOfbody1';
import AnyOfbody2 from './model/AnyOfbody2';
import AnyOfbody3 from './model/AnyOfbody3';
import Body from './model/Body';
import Body1 from './model/Body1';
import Body2 from './model/Body2';
import Body3 from './model/Body3';
import CollectImageMulticlass from './model/CollectImageMulticlass';
import CollectImageMulticlassForm from './model/CollectImageMulticlassForm';
import CollectImageMultilabel from './model/CollectImageMultilabel';
import CollectImageMultilabelForm from './model/CollectImageMultilabelForm';
import CollectTextMulticlass from './model/CollectTextMulticlass';
import CollectTextMultilabel from './model/CollectTextMultilabel';
import ImageInference from './model/ImageInference';
import ImageInferenceBatch from './model/ImageInferenceBatch';
import ObjectDetection from './model/ObjectDetection';
import ObjectDetectionForm from './model/ObjectDetectionForm';
import ObjectDetectionImage from './model/ObjectDetectionImage';
import ObjectDetectionObjects from './model/ObjectDetectionObjects';
import TextExtraction from './model/TextExtraction';
import TextExtractionEntity1 from './model/TextExtractionEntity1';
import TextInference from './model/TextInference';
import TextInferenceBatch from './model/TextInferenceBatch';
import ImageClassificationMulticlassApi from './api/ImageClassificationMulticlassApi';
import ImageClassificationMultilabelApi from './api/ImageClassificationMultilabelApi';
import ObjectDetectionApi from './api/ObjectDetectionApi';
import TextClassificationMulticlassApi from './api/TextClassificationMulticlassApi';
import TextClassificationMultilabelApi from './api/TextClassificationMultilabelApi';
import TextExtractionApi from './api/TextExtractionApi';

/**
* This_is_Skyl_ai_API_documentation_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SkylaiApiDocumentation = require('index'); // See note below*.
* var xxxSvc = new SkylaiApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SkylaiApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SkylaiApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SkylaiApiDocumentation.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnyOfbody model constructor.
     * @property {module:model/AnyOfbody}
     */
    AnyOfbody,

    /**
     * The AnyOfbody1 model constructor.
     * @property {module:model/AnyOfbody1}
     */
    AnyOfbody1,

    /**
     * The AnyOfbody2 model constructor.
     * @property {module:model/AnyOfbody2}
     */
    AnyOfbody2,

    /**
     * The AnyOfbody3 model constructor.
     * @property {module:model/AnyOfbody3}
     */
    AnyOfbody3,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The Body1 model constructor.
     * @property {module:model/Body1}
     */
    Body1,

    /**
     * The Body2 model constructor.
     * @property {module:model/Body2}
     */
    Body2,

    /**
     * The Body3 model constructor.
     * @property {module:model/Body3}
     */
    Body3,

    /**
     * The CollectImageMulticlass model constructor.
     * @property {module:model/CollectImageMulticlass}
     */
    CollectImageMulticlass,

    /**
     * The CollectImageMulticlassForm model constructor.
     * @property {module:model/CollectImageMulticlassForm}
     */
    CollectImageMulticlassForm,

    /**
     * The CollectImageMultilabel model constructor.
     * @property {module:model/CollectImageMultilabel}
     */
    CollectImageMultilabel,

    /**
     * The CollectImageMultilabelForm model constructor.
     * @property {module:model/CollectImageMultilabelForm}
     */
    CollectImageMultilabelForm,

    /**
     * The CollectTextMulticlass model constructor.
     * @property {module:model/CollectTextMulticlass}
     */
    CollectTextMulticlass,

    /**
     * The CollectTextMultilabel model constructor.
     * @property {module:model/CollectTextMultilabel}
     */
    CollectTextMultilabel,

    /**
     * The ImageInference model constructor.
     * @property {module:model/ImageInference}
     */
    ImageInference,

    /**
     * The ImageInferenceBatch model constructor.
     * @property {module:model/ImageInferenceBatch}
     */
    ImageInferenceBatch,

    /**
     * The ObjectDetection model constructor.
     * @property {module:model/ObjectDetection}
     */
    ObjectDetection,

    /**
     * The ObjectDetectionForm model constructor.
     * @property {module:model/ObjectDetectionForm}
     */
    ObjectDetectionForm,

    /**
     * The ObjectDetectionImage model constructor.
     * @property {module:model/ObjectDetectionImage}
     */
    ObjectDetectionImage,

    /**
     * The ObjectDetectionObjects model constructor.
     * @property {module:model/ObjectDetectionObjects}
     */
    ObjectDetectionObjects,

    /**
     * The TextExtraction model constructor.
     * @property {module:model/TextExtraction}
     */
    TextExtraction,

    /**
     * The TextExtractionEntity1 model constructor.
     * @property {module:model/TextExtractionEntity1}
     */
    TextExtractionEntity1,

    /**
     * The TextInference model constructor.
     * @property {module:model/TextInference}
     */
    TextInference,

    /**
     * The TextInferenceBatch model constructor.
     * @property {module:model/TextInferenceBatch}
     */
    TextInferenceBatch,

    /**
    * The ImageClassificationMulticlassApi service constructor.
    * @property {module:api/ImageClassificationMulticlassApi}
    */
    ImageClassificationMulticlassApi,

    /**
    * The ImageClassificationMultilabelApi service constructor.
    * @property {module:api/ImageClassificationMultilabelApi}
    */
    ImageClassificationMultilabelApi,

    /**
    * The ObjectDetectionApi service constructor.
    * @property {module:api/ObjectDetectionApi}
    */
    ObjectDetectionApi,

    /**
    * The TextClassificationMulticlassApi service constructor.
    * @property {module:api/TextClassificationMulticlassApi}
    */
    TextClassificationMulticlassApi,

    /**
    * The TextClassificationMultilabelApi service constructor.
    * @property {module:api/TextClassificationMultilabelApi}
    */
    TextClassificationMultilabelApi,

    /**
    * The TextExtractionApi service constructor.
    * @property {module:api/TextExtractionApi}
    */
    TextExtractionApi
};
